BananasFits/Web/ViewModels/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Web.ViewModels
{
    public class LoginViewModel
    {
        [Required]
        [DataType(DataType.EmailAddress)]
        public virtual string Email { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public virtual string Password { get; set; }
    }
}

BananasFits/Web/ViewModels/UsuarioViewModel.cs
using Processo.Entidades;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Web.ViewModels
{
    #region Cadastro
    public class CadastroUsuarioViewModel
    {
        [Required]
        public virtual string Email { get; set; }
        [Required]
        public virtual string Password { get; set; }
        public virtual bool IsHabilitado { get; set; }
        [RegularExpression("[0-9()-]+", ErrorMessage = "Este campo aceita apenas números")]
        public virtual string Celular { get; set; }
        [Required]
        [RegularExpression("[0-9()-]+", ErrorMessage = "Este campo aceita apenas números")]
        public virtual string Telefone { get; set; }
        public virtual CadastrarEnderecoViewModel Endereco { get; set; }
        public virtual int Tipo { get; set; }
        [Required]
        [MaxLength(50)]
        [RegularExpression("[a-z A-ZáéíóúÁÉÍÓÚÇçÃÕãõâêôûîÂÊÎÔÛ]+", ErrorMessage = "Este campo aceita apenas letras")]
        public virtual string Nome { get; set; }
    }

    public class CadastroPessoaJuridicaViewModel : CadastroUsuarioViewModel
    {
        [Required]
        [MaxLength(20)]
        [RegularExpression("[0-9.-]+", ErrorMessage = "Este campo aceita apenas números")]
        public virtual string CNPJ { get; set; }
        public virtual string LocalizacaoX { get; set; }
        public virtual string LocalizacaoY { get; set; }
        public virtual HttpPostedFileBase Imagem { get; set; }
        [Required]
        [MaxLength(200)]
        [RegularExpression("[a-z A-ZáéíóúÁÉÍÓÚÇçÃÕãõâêôûîÂÊÎÔÛ]+", ErrorMessage = "Este campo aceita apenas letras")]
        public virtual string Descricao { get; set; }
        [Required]
        [MaxLength(50)]
        [RegularExpression("[a-z A-ZáéíóúÁÉÍÓÚÇçÃÕãõâêôûîÂÊÎÔÛ0-9]+", ErrorMessage = "Este campo aceita apenas letras")]
        public virtual string RazaoSocial { get; set; }
    }

    public class CadastroPessoaFisicaViewModel : CadastroUsuarioViewModel
    {
        [Required]
        [MaxLength(15)]
        [RegularExpression("[0-9.-]+", ErrorMessage = "Este campo aceita apenas números")]
        public virtual string CPF { get; set; }
        public virtual int QuantidadeMoedas { get; set; }
        public virtual bool IsAdministrador { get; set; }
    }
    #endregion

    #region Detalhar
    public class DetalharUsuarioViewModel
    {

        public virtual int Chave { get; set; }
        [Required]
        public virtual string Email { get; set; }
        [Required]
        public virtual string Password { get; set; }
        public virtual bool IsHabilitado { get; set; }
        public virtual string Celular { get; set; }
        public virtual string Telefone { get; set; }
        public virtual CadastrarEnderecoViewModel Endereco { get; set; }
        public virtual int QuantidadeMoedas { get; set; }
        public virtual string Nome { get; set; }
    }
    public class DetalharPessoaFisicaViewModel : DetalharUsuarioViewModel
    {
        public virtual string CPF { get; set; }
    }

    public class DetalharPessoaJuridicaViewModel : DetalharUsuarioViewModel
    {
        public virtual string CNPJ { get; set; }
        public virtual string Imagem { get; set; }
        public virtual string Descricao { get; set; }
        public virtual string RazaoSocial { get; set; }
        public virtual IList<ServicoPessoaJuridica> Servicos { get; set; }
    }
    public class DetalharBuscaPessoaJuridicaViewModel : DetalharPessoaJuridicaViewModel
    {
        public virtual int Avaliacao { get; set; }
        public virtual int QuantidadeAvaliacao { get; set; }
    }
    #endregion

    #region Login
    public class LoginViewModel
    {
        [Required]
        [DataType(DataType.EmailAddress)]
        public virtual string Email { get; set; }
        [Required]
        [DataType(DataType.Password)]
        public virtual string Password { get; set; }
    }
    #endregion

    #region Endereço
    public class CadastrarEnderecoViewModel
    {
        [Required]
        [MaxLength(50)]
        [RegularExpression("[0-9.-]+", ErrorMessage = "Este campo aceita apenas números")]
        public virtual string CEP { get; set; }
        [Required]
        [MaxLength(50)]
        [RegularExpression("[a-z A-ZáéíóúÁÉÍÓÚÇçÃÕãõâêôûîÂÊÎÔÛ]+", ErrorMessage = "Este campo aceita apenas letras")]
        public virtual string Rua { get; set; }
        [MaxLength(50)]
        [RegularExpression("[0-9]+", ErrorMessage = "Este campo aceita apenas números")]
        public virtual string Numero { get; set; }
        [MaxLength(50)]
        public virtual string Complemento { get; set; }
        [Required]
        [MaxLength(50)]
        [RegularExpression("[a-z A-ZáéíóúÁÉÍÓÚÇçÃÕãõâêôûîÂÊÎÔÛ]+", ErrorMessage = "Este campo aceita apenas letras")]
        public virtual string Bairro { get; set; }
        [Required]
        [MaxLength(50)]
        [RegularExpression("[a-z A-ZáéíóúÁÉÍÓÚÇçÃÕãõâêôûîÂÊÎÔÛ]+", ErrorMessage = "Este campo aceita apenas letras")]
        public virtual string Cidade { get; set; }
        [Required]
        [MaxLength(50)]
        public virtual string Estado { get; set; }
    }

    public class RankingViewModel
    {
        public virtual int Pontuacao { get; set; }
        public virtual string Nome { get; set; }
        
    }
    #endregion
}

BananasFits/Web/Controllers/AvaliacaoController.cs
using Processo.Entidades;
using Processo.Negocio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.ViewModels;

namespace Web.Controllers
{
    public class AvaliacaoController : BaseController
    {
        public ActionResult Avaliar(int pontuacao, int chavePessoaJuridica)
        {
            var chaveUsuario = ((UsuarioLogadoModel)Session["usuario"]).Chave;
            var pessoaJuridica = unityOfWork.PessoaJuridicaNegocio.BuscarPorChave(chavePessoaJuridica);
            var pessoaFisica = unityOfWork.PessoaFisicaNegocio.BuscarPorChave(chaveUsuario);
            try
            {
                unityOfWork.AvaliacaoNegocio.Avaliar(new Avaliacao
                {
                    PessoaFisica = pessoaFisica,
                    PessoaJuridica = pessoaJuridica,
                    Pontuacao = pontuacao
                });
                unityOfWork.Commit();
            }
            catch (NegocioException ex)
            {
                TratarMensagemException(ex);
            }

            return RedirectToAction("DetalharPessoaJuridica", "Usuario", new { chave = chavePessoaJuridica });
        }

        public ActionResult Index()
        {
            return View();
        }
    }
}

BananasFits/Web/Controllers/MovimentacaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.ViewModels;
using PagedList;
using Processo.Entidades;
using NPOI.SS.UserModel;
using NPOI.XSSF.UserModel;
using System.IO;
using PayPal.Api.Payments;
using PayPal;

namespace Web.Controllers
{
    public class MovimentacaoController : BaseController
    {
        private const int valorFit = 5;

        #region View Comprar Fits
        public ActionResult ComprarFits()
        {
            if(Session["usuario"] == null)
            {
                ExibirMensagemErro("Você precisa estar logado para efetuar esta compra.");
                return RedirectToAction("Index", "Home");
            }
            ViewBag.MesVencimento = new List<SelectListItem> 
            {
                new SelectListItem{ Text = "Janeiro", Value = "01"},
                new SelectListItem{ Text = "Fevereiro", Value = "02"},
                new SelectListItem{Text = "Março", Value = "03"},
                new SelectListItem{Text = "Abril", Value = "04"},
                new SelectListItem{Text = "Maio", Value = "05"},
                new SelectListItem{Text = "Junho", Value = "06"},
                new SelectListItem{Text = "Julho", Value = "07"},
                new SelectListItem{Text = "Agosto", Value = "08"},
                new SelectListItem{Text = "Setembro", Value = "09"},
                new SelectListItem{Text = "Outubro", Value = "10"},
                new SelectListItem{Text = "Novembro", Value = "11"},
                new SelectListItem{Text = "Dezembro", Value = "12"},
            };
            List<SelectListItem> anos = new List<SelectListItem>();

            for (int i = 0; i < 11; i++)
            {
                anos.Add(new SelectListItem
                {
                    Value = DateTime.Now.AddYears(i).Year.ToString(),
                    Text = DateTime.Now.AddYears(i).Year.ToString()
                });
            }
            ViewBag.AnoVencimento = anos;

            ViewBag.TipoCartao = new List<SelectListItem> 
            {
                new SelectListItem{ Text = "Visa", Value = "visa"},
                new SelectListItem{ Text = "MasterCard", Value = "master"},
            };

            ViewBag.Valor = new List<SelectListItem> 
            {
                new SelectListItem{ Text = "1 Fit ->  R$5,00", Value = "1"},
                new SelectListItem{ Text = "5 Fits ->  R$25,00", Value = "5"},
                new SelectListItem{ Text = "10 Fits ->  R$50,00", Value = "10"},
                new SelectListItem{ Text = "15 Fits ->  R$75,00", Value = "15"},
            };

            return View();
        }
        [HttpPost]
        public ActionResult ComprarFits(ComprarFitsViewModel model)
        {
            Util.PayPalNegocio paypalNegocio = new Util.PayPalNegocio("AUoYdBAqgl5mugEOu-xrxNeLj0DW2CohcYODtyxzsozi-me48ymybDi6dtw2",
          "ELyImxCvpvxoiFRyfqzScMZbfo84f2Au4l-TJX78ymKuHskG_pDAcJHHt3uf", "sandbox", 5);

            var usuario = (UsuarioLogadoModel)Session["usuario"];

            CreditCard creditCard = new CreditCard();
            creditCard.number = model.NumeroCartao;
            creditCard.type = model.TipoCartao;
            creditCard.expire_month = Convert.ToInt32(model.Mes);
            creditCard.expire_year = Convert.ToInt32(model.Ano);
            creditCard.first_name = usuario.Email;
            creditCard.cvv2 = Convert.ToInt32(model.Cvv);


            if (usuario.IsPessoaFisica)
            {
                var pessoaFisica = unityOfWork.PessoaFisicaNegocio.BuscarPorChave(usuario.Chave);
                //realizou pagamento
                var valor = paypalNegocio.EfetuarCompra(pessoaFisica,
                    creditCard, model.QuantidadeFits);
                //creditou fits
                unityOfWork.PessoaFisicaNegocio.CreditarFits(pessoaFisica, model.QuantidadeFits, valor);
                unityOfWork.Commit();
            }
            else
                ExibirMensagemErro("Compra não autorizada para usuários que sejam pessoa jurídica.");

            ExibirMensagemSucesso("Compra realizada com sucesso.");
            return RedirectToAction("ComprarFits");
        }
        #endregion

        #region View Historico Compra Fitis
        public ActionResult ListarHistoricoCompraFits(int? page)
        {
            var usuario = (UsuarioLogadoModel)Session["usuario"];
            if (usuario != null && usuario.IsPessoaFisica)
            {
                IEnumerable<HistoricoCompraFits> historicoCompraFits = new List<HistoricoCompraFits>();
                if (usuario.IsAdministrador)
                    historicoCompraFits = unityOfWork.HistoricoCompraFitsNegocio.ConsultarTodos();
                else
                    historicoCompraFits = unityOfWork.HistoricoCompraFitsNegocio.Consultar(e => e.PessoaFisica.Chave == usuario.Chave);

                historicoCompraFits = historicoCompraFits.OrderByDescending(e => e.DataCompra);

                int pageSize = 10;
                int pageNumber = (page ?? 1);

                return View(historicoCompraFits.ToPagedList(pageNumber, pageSize));
            }
            ExibirMensagemErro("Esta ação não é permitida.");
            return RedirectToAction("Index", "Home");
        }

        #endregion

        #region Listar Histórico de Serviços
        public ActionResult ListarHistoricoServico(string pessoaFisica, string academia,
            DateTime? dataInicial, DateTime? dataFinal, int? page)
        {
            var usuario = (UsuarioLogadoModel)Session["usuario"];
            if (usuario != null)
            {
                var historicoCompraServico = GerarHistoricoServico(usuario, pessoaFisica, academia, dataInicial, dataFinal, page);
                ViewBag.PessoaFisica = pessoaFisica;
                ViewBag.Academia = academia;
                ViewBag.DataInicial = dataInicial;
                ViewBag.DataFinal = dataFinal;
                ViewBag.Total = historicoCompraServico.Sum(e => e.Valor);

                historicoCompraServico = historicoCompraServico.OrderByDescending(e => e.Data);

                int pageSize = 10;
                int pageNumber = (page ?? 1);

                return View(historicoCompraServico.ToPagedList(pageNumber, pageSize));
            }
            return RedirectToAction("Index", "Home");
        }

        public ActionResult GerarExcel(string pessoaFisica, string academia,
            DateTime? dataInicial, DateTime? dataFinal, int? page)
        {
            var usuario = (UsuarioLogadoModel)Session["usuario"];
            var historico = GerarHistoricoServico(usuario, pessoaFisica, academia, dataInicial, dataFinal, null);

            IWorkbook workbook = new XSSFWorkbook();

            ISheet sheet = workbook.CreateSheet("Historico");

            int rowNumer = 0;

            IRow row = sheet.CreateRow(rowNumer);
            ICell cell;

            ICellStyle style = workbook.CreateCellStyle();
            style.FillForegroundColor = NPOI.HSSF.Util.HSSFColor.Grey25Percent.Index;
            style.FillPattern = FillPattern.SolidForeground;

            cell = row.CreateCell(0);
            cell.SetCellValue("Pessoa Física");
            cell.CellStyle = style;

            cell = row.CreateCell(1);
            cell.SetCellValue("Serviço");
            cell.CellStyle = style;

            cell = row.CreateCell(2);
            cell.SetCellValue("Academia");
            cell.CellStyle = style;

            cell = row.CreateCell(3);
            cell.SetCellValue("Data");
            cell.CellStyle = style;

            cell = row.CreateCell(4);
            cell.SetCellValue("Valor");
            cell.CellStyle = style;

            //---- row

            foreach (var item in historico)
            {
                rowNumer++;
                row = sheet.CreateRow(rowNumer);
                row.CreateCell(0).SetCellValue(item.NomePessoaFisica);
                row.CreateCell(1).SetCellValue(item.NomeServico);
                row.CreateCell(2).SetCellValue(item.NomePessoaJuridica);
                row.CreateCell(3).SetCellValue(item.Data.ToString());
                row.CreateCell(4).SetCellFormula(item.Valor.ToString());

            }

            MemoryStream stream = new MemoryStream();
            workbook.Write(stream);

            return File(stream.ToArray(), //The binary data of the XLS file
                "application/vnd.ms-excel", //MIME type of Excel files
                string.Format("HistoricoCompraServico.xlsx", DateTime.Now.ToString("yyyy-MM-dd_HH-mm-ss")));
        }

        public IEnumerable<HistoricoCompraServico> GerarHistoricoServico(UsuarioLogadoModel usuario, string pessoaFisica, string academia,
            DateTime? dataInicial, DateTime? dataFinal, int? page)
        {

            IEnumerable<HistoricoCompraServico> historicoCompraServico;
            if (usuario.IsAdministrador)
                historicoCompraServico = unityOfWork.HistoricoCompraServicoNegocio.ConsultarTodos();
            else if (usuario.IsPessoaFisica)
            {
                historicoCompraServico = unityOfWork.HistoricoCompraServicoNegocio.Consultar(e => e.PessoaFisica.Chave == usuario.Chave);
            }
            else
            {
                historicoCompraServico = unityOfWork.HistoricoCompraServicoNegocio.Consultar(e => e.Servico.PessoaJuridica.Chave == usuario.Chave);
            }
            if (!string.IsNullOrEmpty(academia))
            {
                historicoCompraServico = historicoCompraServico.Where(e => e.NomePessoaJuridica.ToUpper().Contains(academia.ToUpper()));
            }
            if (dataInicial != null && dataFinal != null)

BananasFits/Web/Views/Usuario/DetalharPessoaJuridica.cshtml
@model Web.ViewModels.DetalharBuscaPessoaJuridicaViewModel


<div class="container">
    <div class="clearfix panel">
        <br>
        <div class="col-md-12">
            <div class="col-md-6 col-sm-6 col-lg-6 ">
                <img src="@Model.Imagem" class="img-responsive col-md-offset-3" alt="imagem academia" style="max-width: 300px; max-height: 300px;" />
            </div>
            <div class="col-md-6 col-sm-6 col-lg-6">
                <h2 class="text-center">
                    @Model.Nome
                </h2>
                <p>
                    @Model.Descricao
                </p>
            </div>


            <br /><br /><br />
            <div class="col-md-12 col-sm-12 col-lg-12" style="margin-top:50px; padding-bottom:50px;text-align:center;">
                <div class="row clearfix col-md-3 col-sm-3">
                    <div class="col-md-2  column">
                        <span class="glyphicon glyphicon-earphone" style="font-size: 60px; margin-left:-20px;"></span>
                    </div>
                    <div class="col-md-10 column" style="margin-top: -20px;">
                        <h3>Contato</h3>
                        Telefone: @Model.Telefone<br />
                        Celular: @Model.Celular

                    </div>
                    <br><br>
                </div>
                <div class="row clearfix col-md-4 col-sm-4 col-sm-offset-1 col-md-offset-1">
                    <div class="col-md-2 column">
                        <span class="glyphicon glyphicon-map-marker" style="font-size: 60px; margin-left: -20px;"></span>
                    </div>
                    <div class="col-md-10 column " style="margin-top: -20px;">
                        <h3>Localização</h3>
                        @Model.Endereco.Rua @Model.Endereco.Numero @Model.Endereco.Complemento <br /> @Model.Endereco.Bairro - @Model.Endereco.Cidade - @Model.Endereco.Estado <br /><br />
                        <a class=" btn-block btn-info" style="padding:10px;" href="https://www.google.com.br/maps/place/@Model.Endereco.Rua,@Model.Endereco.Numero @Model.Endereco.Cidade - @Model.Endereco.Estado" target="_blank">Ver no mapa!</a>
                    </div>
                    <br><br>
                </div>
                <div class="row clearfix col-md-3 col-sm-3 col-sm-offset-1 col-md-offset-1">
                    <div class="col-md-2 column">
                        <span class="glyphicon glyphicon-stats" accesskey="" style="font-size: 60px; margin-left: -20px;"></span>
                    </div>
                    <div class="col-md-10 column " style="margin-top: -20px;">

                        <h3>RANKING </h3>
                        <div style="font-size:18px;">
                            @if (Session["usuario"] != null && ((Web.ViewModels.UsuarioLogadoModel)Session["usuario"]).IsPessoaFisica)
                            {
                                <input type="hidden" value="@Model.Avaliacao" id="avaliacao" />
                                <a href="@Url.Action("Avaliar", "Avaliacao", new { pontuacao = 1, chavePessoaJuridica = @Model.Chave })" id="avaliar1" class="glyphicon glyphicon-star-empty"></a>
                                <a href="@Url.Action("Avaliar", "Avaliacao", new { pontuacao = 2, chavePessoaJuridica = @Model.Chave })" id="avaliar2" class="glyphicon glyphicon-star-empty"></a>
                                <a href="@Url.Action("Avaliar", "Avaliacao", new { pontuacao = 3, chavePessoaJuridica = @Model.Chave })" id="avaliar3" class="glyphicon glyphicon-star-empty"></a>
                                <a href="@Url.Action("Avaliar", "Avaliacao", new { pontuacao = 4, chavePessoaJuridica = @Model.Chave })" id="avaliar4" class="glyphicon glyphicon-star-empty"></a>
                                <a href="@Url.Action("Avaliar", "Avaliacao", new { pontuacao = 5, chavePessoaJuridica = @Model.Chave })" id="avaliar5" class="glyphicon glyphicon-star-empty"></a>
                                <br />

                            }

                            else
                            {
                                <label style="font-size:15px"><span class="glyphicon glyphicon-user"></span>  @Model.QuantidadeAvaliacao  total</label><br /><br />
                                <a href="@Url.Action("Login", "Usuario")" class="btn-block btn-info" style="font-size:12px; padding:10px;">Faça o login para avaliar!</a>
                            }

                            <script>
                                if ($("#avaliacao").val() == 1) {
                                    $("#avaliar1").removeClass("glyphicon glyphicon-star-empty");
                                    $("#avaliar1").addClass("glyphicon glyphicon-star");
                                }
                                if ($("#avaliacao").val() == 2) {
                                    $("#avaliar1").removeClass("glyphicon glyphicon-star-empty");
                                    $("#avaliar2").removeClass("glyphicon glyphicon-star-empty");
                                    $("#avaliar1").addClass("glyphicon glyphicon-star");
                                    $("#avaliar2").addClass("glyphicon glyphicon-star");

                                }
                                if ($("#avaliacao").val() == 3) {
                                    $("#avaliar1").removeClass("glyphicon glyphicon-star-empty");
                                    $("#avaliar2").removeClass("glyphicon glyphicon-star-empty");
                                    $("#avaliar3").removeClass("glyphicon glyphicon-star-empty");
                                    $("#avaliar1").addClass("glyphicon glyphicon-star");
                                    $("#avaliar2").addClass("glyphicon glyphicon-star");
                                    $("#avaliar3").addClass("glyphicon glyphicon-star");
                                }
                                if ($("#avaliacao").val() == 4) {
                                    $("#avaliar1").removeClass("glyphicon glyphicon-star-empty");
                                    $("#avaliar2").removeClass("glyphicon glyphicon-star-empty");
                                    $("#avaliar3").removeClass("glyphicon glyphicon-star-empty");
                                    $("#avaliar4").removeClass("glyphicon glyphicon-star-empty");
                                    $("#avaliar1").addClass("glyphicon glyphicon-star");
                                    $("#avaliar2").addClass("glyphicon glyphicon-star");
                                    $("#avaliar3").addClass("glyphicon glyphicon-star");
                                    $("#avaliar4").addClass("glyphicon glyphicon-star");
                                }
                                if ($("#avaliacao").val() == 5) {
                                    $("#avaliar1").removeClass("glyphicon glyphicon-star-empty");
                                    $("#avaliar2").removeClass("glyphicon glyphicon-star-empty");
                                    $("#avaliar3").removeClass("glyphicon glyphicon-star-empty");
                                    $("#avaliar4").removeClass("glyphicon glyphicon-star-empty");
                                    $("#avaliar5").removeClass("glyphicon glyphicon-star-empty");
                                    $("#avaliar1").addClass("glyphicon glyphicon-star");
                                    $("#avaliar2").addClass("glyphicon glyphicon-star");
                                    $("#avaliar3").addClass("glyphicon glyphicon-star");
                                    $("#avaliar4").addClass("glyphicon glyphicon-star");
                                    $("#avaliar5").addClass("glyphicon glyphicon-star");
                                }

                            </script>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row clearfix" style="text-align: center;">
                <div class="col-md-12 col-sm-12 col-lg-12">
                    <h2>
                        Serviços disponíveis
                    </h2>
                </div>
            </div><br>
            <div class="col-lg-12 col-md-12" style="text-align: center;">
                @foreach (var item in Model.Servicos)
                {
                    <div class="col-md-2 column ">
                        <h3>
                            @item.Servico.Nome
                        </h3>
                        <img alt="140x140" src="@item.Servico.Imagem" class="img-rounded" style="width:150px; height:150px;" />
                        <h3>
                            @item.Valor Fits
                        </h3>
                    </div>

                }

            </div><br>
            <div class="row">
                <div class="col-lg-12" style="text-align: center; margin-left: 0px;">
                    <a href="@Url.Action("ComprarFits","Movimentacao")" class="btn btn-success btn-lg " role="button"><span class="glyphicon glyphicon-shopping-cart"></span> Comprar Fits!</a>
                </div>
            </div>
            <br><br><br>
        </div>
    </div>
</div>

BananasFits/Web/Views/Usuario/ListarPessoaFisica.cshtml
@model PagedList.IPagedList<Processo.Entidades.PessoaFisica>
@using PagedList.Mvc;

<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-10 col-lg-10 col-xs-offset-0 col-sm-offset-0 col-md-offset-1 col-lg-offset-1 toppad">
            <div class="panel panel-">
                <div class="panel-heading">
                    <h1 class="panel-title">
                        <span style="font-size:25px; font-weight:bold;">Lista de Pessoas Físicas</span>
                    </h1>
                </div>
                <div class="panel-body">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="table-responsive">
                                    <table id="mytable" class="table table-bordred table-striped">
                                        <thead>
                                            <tr>
                                               
                                                <th>ID</th>
                                                <th>Nome</th>
                                                <th>CPF</th>
                                                <th>Inativar</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            @foreach (var item in Model)
                                            {
                                                <tr>
                                                    <td>@item.Chave</td>
                                                    <td>@item.Nome</td>
                                                    <td>@item.CPF</td>
                                                    <td><p><a href="@Url.Action("InativarPessoaFisica","Usuario", new {chave = item.Chave})" class="btn btn-danger btn-xs" data-title="Delete" rel="tooltip"><span class="glyphicon glyphicon-trash"></span></a></p></td>
                                                </tr>
                                            }
                                        </tbody>
                                    </table>
                                    <div class="clearfix"></div>

                                    @Html.PagedListPager(Model, page => Url.Action("ListarPessoaFisica", new { page, }))
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div><br /><br />